docRoot                   $VH_ROOT/doc/
enableGzip                1

errorlog $VH_ROOT/logs/error.log {
  useServer               0
  logLevel                NOTICE
  rollingSize             10M
}

accesslog $VH_ROOT/logs/access.log {
  useServer               0
  logHeaders              7
  rollingSize             10M
  keepDays                30
  compressArchive         0
}

index  {
  useServer               1
  indexFiles              index.html, index.php
  autoIndex               0
  autoIndexURI            /_autoindex/default.php
}

errorpage 404 {
  url                     /error404.html
}

expires  {
  enableExpires           1
}

phpIniOverride  {
  php_admin_value date.timezone           Asia/Shanghai
  php_admin_value max_execution_time      300
  php_admin_value memory_limit            256M
  php_admin_value post_max_size           256M
  php_admin_value upload_max_filesize     256M
  php_admin_value max_input_vars          3000
  php_admin_value expose_php              Off
}

accessControl  {
  allow                   *
}

realm SampleProtectedArea {
  userDB  {
    location              conf/vhosts/$VH_NAME/htpasswd
    maxCacheSize          200
    cacheTimeout          60
  }

  groupDB  {
    location              conf/vhosts/$VH_NAME/htgroup
    maxCacheSize          200
    cacheTimeout          60
  }
}

context / {
  location                $DOC_ROOT/
  allowBrowse             1

  extraHeaders            <<<END_extraHeaders
Access-Control-Allow-Origin *
Feature-Policy "geolocation 'self'; midi 'self'; sync-xhr 'self'; microphone 'self'; camera 'self'; magnetometer 'self'; gyroscope 'self'; speaker 'self'; fullscreen 'self'; payment 'self'; usb 'self'"
Referrer-Policy strict-origin-when-cross-origin
Strict-Transport-Security max-age=31536000; preload; includeSubDomains; always
X-Content-Type-Options nosniff; always
X-Download-Options noopen
X-Frame-Options SAMEORIGIN
X-Powered-By OLS-Optimized
X-XSS-Protection 1; mode=block
  END_extraHeaders

  rewrite  {
    enable                1
  }
}

context /docs/ {
  location                $SERVER_ROOT/docs/
  allowBrowse             1
}

context /protected/ {
  location                protected/
  allowBrowse             1
  realm                   SampleProtectedArea
  authName                Protected
  required                user test

  accessControl  {
    allow                 *
  }
}

context /blocked/ {
  allowBrowse             0
}

context /cgi-bin/ {
  type                    cgi
  location                $VH_ROOT/cgi-bin/
}

rewrite  {
  enable                  1
  autoLoadHtaccess        1
  logLevel                0
}
